import pathlib

import abjad
import baca
import evans

import undae

maker = evans.SegmentMaker(
    instruments=undae.instruments,
    names=[
        '"Violin I"',
        '"Violin II"',
        '"Viola"',
        '"Violoncello"',
    ],
    abbreviations=[
        '"vn. I"',
        '"vn. II"',
        '"va."',
        '"vc."',
    ],
    name_staves=True,
    fermata_measures=undae.fermata_measures_07,
    commands=[
        evans.MusicCommand(
            [("violin 1 voice", [_ for _ in range(5)])],
            evans.talea([5, 9], 4, rewrite=-1),
            evans.PitchHandler(["ef,,,"]),
            evans.PitchHandler(["28/1", "20/1"], as_ratios=True),
            evans.force_accidentals,
            undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [_ for _ in range(18, 25)])],
            evans.talea([5, 9], 4, rewrite=-1),
            evans.PitchHandler(["ef,,,"]),
            evans.PitchHandler(["28/1", "20/1"], as_ratios=True),
            evans.force_accidentals,
            undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [_ for _ in range(5)])],
            evans.talea([7, 5], 4, rewrite=-1),
            evans.PitchHandler(["ef,,,"]),
            evans.PitchHandler(["32/1", "21/1"], as_ratios=True),
            evans.force_accidentals,
            undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [_ for _ in range(18, 25)])],
            evans.talea([6, 7, 5], 4, rewrite=-1),
            evans.PitchHandler(["ef,,,"]),
            evans.PitchHandler(["32/1", "21/1"], as_ratios=True),
            evans.force_accidentals,
            undae.A_color,
        ),
        evans.MusicCommand(
            [("cello voice", [23, 24])],
            evans.talea([6], 4, rewrite=-1),
            evans.PitchHandler(["ef,,,"]),
            evans.PitchHandler(["29/1", "25/1"], as_ratios=True),
            evans.force_accidentals,
            abjad.Clef("treble"),
            undae.A_color,
        ),
        evans.call(
            "score",
            evans.annotate_concurrent_ratios,
            lambda _: abjad.select.components(_, abjad.Score),
        ),
        evans.MusicCommand(
            [("violin 1 voice", [_ for _ in range(5, 11)])],
            evans.talea(
                [2],
                8,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([["ef'", "gf'"]]),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [_ for _ in range(11, 16)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.PitchHandler([0, 2, 2.5, 3, 1.5, -3.5, -3, 1, 0.5]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/9", "1/9", "2/9", "1/9", "3/9", "2/9"], padding=2.5),
            evans.trill(alteration="+P5", harmonic=True, padding=6),
            undae.C_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [16, 17])],
            evans.talea(
                [2],
                8,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(["b"]),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [_ for _ in range(5, 11)])],
            evans.talea(
                [2],
                8,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(["bf"]),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [_ for _ in range(11, 16)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.PitchHandler([0, 2, 2.5, 3, 1.5, -3.5, -3, 1, 0.5]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/8", "1/8", "2/8", "1/8", "3/8", "2/8"], padding=2.5),
            evans.trill(alteration="+P4", harmonic=True, padding=6),
            undae.C_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [16, 17])],
            evans.talea(
                [2],
                8,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([["ef'", "f'"]]),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("viola voice", [_ for _ in range(5)])],
            evans.talea(
                [2],
                8,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(["gf"]),
            abjad.Clef("alto"),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("viola voice", [_ for _ in range(5, 15)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.PitchHandler([0, 2, 2.5, 3, 1.5, -3.5, -3, 1, 0.5]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/7", "1/7", "2/7", "1/7", "3/7", "2/7"], padding=2.5),
            evans.trill(alteration="+M3", harmonic=True, padding=6),
            undae.C_color,
        ),
        evans.MusicCommand(
            [("viola voice", [15, 16, 17])],
            evans.talea(
                [2],
                8,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(["gf"]),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("viola voice", [_ for _ in range(18, 25)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.PitchHandler([0, 2, 2.5, 3, 1.5, -3.5, -3, 1, 0.5]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/7", "1/7", "2/7", "1/7", "3/7", "2/7"], padding=2.5),
            # evans.trill(alteration="+m3", harmonic=True, padding=6),
            undae.C_color,
        ),
        evans.MusicCommand(
            [("cello voice", [_ for _ in range(5)])],
            evans.talea(
                [2],
                8,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([["ef,", "bf,", "f"]]),
            abjad.Clef("bass"),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("cello voice", [_ for _ in range(5, 15)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.PitchHandler([0, 2, 2.5, 3, 1.5, -3.5, -3, 1, 0.5]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/6", "1/6", "2/6", "1/6", "3/6", "2/6"], padding=2.5),
            evans.trill(alteration="+M2", harmonic=True, padding=6),
            undae.C_color,
        ),
        evans.MusicCommand(
            [("cello voice", [15, 16, 17])],
            evans.talea(
                [2],
                8,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([["c,", "g,"]]),
            undae.B_color,
        ),
        evans.MusicCommand(
            [("cello voice", [_ for _ in range(18, 23)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.PitchHandler([0, 2, 2.5, 3, 1.5, -3.5, -3, 1, 0.5]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/9", "1/9", "2/9", "1/9", "3/9", "2/9"], padding=2.5),
            evans.trill(alteration="+P4", harmonic=True, padding=6),
            undae.C_color,
        ),
        evans.call(
            "score",
            evans.SegmentMaker.beam_score_without_splitting,
            lambda _: abjad.select.components(_, abjad.Score),
        ),
        evans.attach(
            "Global Context",
            undae.met_111,
            lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "Global Context",
            undae.mark_111,
            lambda _: abjad.select.leaf(_, 0),
        ),
    ],
    score_template=undae.score,
    transpose_from_sounding_pitch=True,
    time_signatures=undae.signatures_07,
    clef_handlers=None,
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        f"{pathlib.Path(abjad.__file__).parent.parent}/docs/source/_stylesheets/abjad.ily",
        f"{pathlib.Path(__file__).parent}/../../build/segment_stylesheet.ily",
    ],
    segment_name="07",
    current_directory=pathlib.Path(__file__).resolve().parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=True,
    barline="||",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    mm_rests=False,
    extra_rewrite=False,
    print_clock_time=True,
)

maker.build_segment()
