import pathlib

import abjad
import baca
import evans

import undae

maker = evans.SegmentMaker(
    instruments=undae.instruments,
    names=[
        '"Violin I"',
        '"Violin II"',
        '"Viola"',
        '"Violoncello"',
    ],
    abbreviations=[
        '"vn. I"',
        '"vn. II"',
        '"va."',
        '"vc."',
    ],
    name_staves=True,
    fermata_measures=undae.fermata_measures_05,
    commands=[
        evans.MusicCommand(
            [("violin 1 voice", [2, 3])],
            evans.note(),
            evans.PitchHandler(["g'"]),
            evans.PitchHandler(["5/4", "7/6"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mf"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [5, 6, 7, 8, 9])],
            evans.note(),
            evans.PitchHandler(["g'"]),
            evans.PitchHandler(
                ["6/5", "16/15", "6/5", "16/15", "55/54"], as_ratios=True
            ),
            evans.force_accidentals,
            abjad.Dynamic("mp"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [11, 12, 13])],
            evans.note(),
            evans.PitchHandler(["g'"]),
            evans.PitchHandler(["55/54", "112/117", "224/243"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mf"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [14, 15, 16])],
            evans.talea([9, 10, 8, 11], 8, rewrite=-1),
            evans.loop([0], [-1, -2]),
            evans.trill(alteration="+P5", harmonic=True, padding=7),
            evans.bcp(["0/7", "1/7", "0/7", "7/7", "2/7", "1/7"], padding=2.5),
            abjad.Dynamic("mp"),
            # undae.C_color,
        ),
        evans.MusicCommand(
            [("violin 1 voice", [18, 19])],
            evans.talea(
                [1],
                16,
                extra_counts=[0, 2, 0, 0, 2, 1, 0, 3],
                preprocessor=evans.make_preprocessor(
                    quarters=True,
                    fuse_counts=[2, 2, 1, 3],
                    split_at_measure_boundaries=True,
                ),
                rewrite=-1,
            ),
            evans.loop([11, 9, 7, 6], [2, -1, -1, 3, -2, 1]),
            abjad.LilyPondLiteral(r"\harmonicsOn", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\harmonicsOff", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([4]),
            evans.text_span([r"scr.", r"norm."], "=>", padding=3.5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=5.5, id=2),
            evans.hairpin("p <| f >", [6]),
            # undae.D_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [2, 3])],
            evans.note(),
            evans.PitchHandler(["g'"]),
            evans.PitchHandler(["1/1"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mf"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [5, 6, 7, 8, 9])],
            evans.note(),
            evans.PitchHandler(["g'"]),
            evans.PitchHandler(
                ["1/1", "14/15", "1/1", "14/15", "25/27"], as_ratios=True
            ),
            evans.force_accidentals,
            abjad.Dynamic("mp"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [10])],
            evans.talea([10, 8, 11, 9], 8, rewrite=-1),
            evans.trill(alteration="+P4", harmonic=True, padding=4),
            abjad.Dynamic("sf"),
            abjad.StartHairpin(">"),
            # undae.C_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [11, 12, 13])],
            evans.note(),
            evans.PitchHandler(["g'"]),
            evans.PitchHandler(["25/27", "448/351", "896/729"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mf"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [15])],
            evans.talea(
                [1],
                16,
                extra_counts=[2, 0, 0, 2, 1, 0, 3, 0],
                preprocessor=evans.make_preprocessor(
                    quarters=True,
                    fuse_counts=[2, 2, 1, 3],
                    split_at_measure_boundaries=True,
                ),
                rewrite=-1,
            ),
            evans.loop([9, 7, 6, 4, 2, 0], [2, -3, 1, 1, -2, -1]),
            abjad.LilyPondLiteral(r"\harmonicsOn", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\harmonicsOff", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6], direction=abjad.UP),
            evans.text_span([r"norm.", "scr."], "=>", padding=3.5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=5.5, id=2),
            evans.hairpin("p < f >", [8]),
            # undae.D_color,
        ),
        evans.MusicCommand(
            [("violin 2 voice", [17, 18, 19])],
            evans.talea(
                [1, 1, 1, 7],
                16,
                extra_counts=[0, 0, 2, 1, 0, 3, 0, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True,
                    fuse_counts=[2, 2, 1, 3],
                    split_at_measure_boundaries=True,
                ),
                rewrite=-1,
            ),
            evans.loop([9, 7, 6, 4, 2, 0], [2, -3, 1, 1, -2, -1]),
            abjad.LilyPondLiteral(r"\harmonicsOn", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\harmonicsOff", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6], direction=abjad.UP),
            evans.text_span([r"scr.", r"norm."], "=>", padding=3.5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=5.5, id=2),
            evans.hairpin("p <| f >", [4]),
            # undae.D_color,
        ),
        evans.MusicCommand(
            [("viola voice", [2, 3])],
            evans.note(),
            evans.PitchHandler(["g"]),
            evans.PitchHandler(["3/2", "5/3"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mf"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("viola voice", [4])],
            evans.talea([8, 11, 9, 10], 8, rewrite=-1),
            evans.trill(alteration="+M3", harmonic=True, padding=4),
            abjad.Dynamic("sf"),
            abjad.StartHairpin(">"),
            # undae.C_color,
        ),
        evans.MusicCommand(
            [("viola voice", [5, 6, 7, 8, 9])],
            evans.note(),
            evans.PitchHandler(["g"]),
            evans.PitchHandler(["8/5", "8/5", "8/5", "8/5", "5/3"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mp"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("viola voice", [11, 12, 13])],
            evans.note(),
            evans.PitchHandler(["g"]),
            evans.PitchHandler(["5/3", "3584/3159", "7168/6561"], as_ratios=True),
            evans.force_accidentals,
            abjad.Dynamic("mf"),
            abjad.Articulation("espressivo"),
            # undae.A_color,
        ),
        evans.MusicCommand(
            [("viola voice", [15])],
            evans.talea(
                [1],
                16,
                extra_counts=[0, 2, 1, 0, 3, 0, 2, 0],
                preprocessor=evans.make_preprocessor(
                    quarters=True,
                    fuse_counts=[2, 2, 1, 3],
                    split_at_measure_boundaries=True,
                ),
                rewrite=-1,
            ),
            evans.loop([9, 7, 6, 5, 6, 7], [2, -3, 1, 1, -2, -1]),
            abjad.LilyPondLiteral(r"\harmonicsOn", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\harmonicsOff", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([3]),
            evans.text_span([r"norm.", "scr."], "=>", padding=3.5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=5.5, id=2),
            evans.hairpin("p < f >", [5]),
            # undae.D_color,
        ),
        evans.MusicCommand(
            [("viola voice", [17, 18, 19])],
            evans.talea(
                [1],
                16,
                extra_counts=[0, 2, 1, 0, 3, 0, 2, 0],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=-1,
            ),
            evans.loop([9, 7, 6, 5, 6, 7], [2, -3, 1, 1, -2, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([3]),
            evans.text_span([r"scr.", r"norm."], "=>", padding=3.5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=5.5, id=2),
            evans.hairpin("p <| f >", [6]),
            # undae.D_color,
        ),
        evans.MusicCommand(
            [("cello voice", [_ for _ in range(18)])],
            evans.talea([11, 9, 10, 8], 8, rewrite=-1),
            evans.loop([_ - 12 for _ in [0, 2, 3, -3]], [-2, -3]),
            lambda _: abjad.glissando(_),
            evans.bcp(["0/8", "1/8", "8/8", "7/8", "6/8", "1/8"], padding=2.5),
            evans.vibrato_spanner(
                peaks=[0, 1, 4, 2, 6, 5],
                wavelengths=[2, 3, 5, 3],
                thickness=0.2,
                divisions=[4, 5, 6],
                padding=6,
            ),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            abjad.Dynamic("mp"),
            # undae.C_color,
        ),
        evans.MusicCommand(
            [("cello voice", [18, 19])],
            evans.talea(
                [1],
                16,
                extra_counts=[1, 0, 3, 0, 2, 0, 0, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True,
                    fuse_counts=[2, 2, 1, 3],
                    split_at_measure_boundaries=True,
                ),
                rewrite=-1,
            ),
            evans.loop([_ - 12 for _ in [9, 7, 6, 4, 2, 0, -1]], [2, -1, -1, 3, -2, 1]),
            abjad.LilyPondLiteral(r"\harmonicsOn", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\harmonicsOff", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([7]),
            evans.text_span([r"norm.", "scr."], "=>", padding=3.5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=5.5, id=2),
            evans.hairpin("p <| f >", [5]),
            # undae.D_color,
        ),
        evans.call(
            "violin 2 voice",
            evans.text_span(["scr."], "=|", padding=2),
            evans.select_measures([10, 11]),
        ),
        evans.call(
            "score",
            evans.SegmentMaker.beam_score_without_splitting,
            lambda _: abjad.select.components(_, abjad.Score),
        ),
        evans.attach(
            "Global Context",
            undae.met_93,
            lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "Global Context",
            undae.mark_93,
            lambda _: abjad.select.leaf(_, 0),
        ),
    ],
    score_template=undae.score,
    transpose_from_sounding_pitch=True,
    transparent_fermatas=False,  # jack parts
    time_signatures=undae.signatures_05,
    clef_handlers=None,
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        f"{pathlib.Path(abjad.__file__).parent.parent}/docs/source/_stylesheets/abjad.ily",
        f"{pathlib.Path(__file__).parent}/../../build/segment_stylesheet.ily",
    ],
    segment_name="05",
    current_directory=pathlib.Path(__file__).resolve().parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=True,
    barline="||",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    mm_rests=False,
    extra_rewrite=False,
    print_clock_time=True,
    # tempo=((1, 4), 93),
)

maker.build_segment()
# maker._make_sc_file()
